finished server

diff --git a/prod1/ex_banking/bin/ex_banking b/prod1/ex_banking/bin/ex_banking
--- a/prod1/ex_banking/bin/ex_banking
+++ b/prod1/ex_banking/bin/ex_banking
@@ -40,7 +40,7 @@ export RELEASE_NAME="ex_banking"
 export RELEASE_VSN="0.1.0"
 export RELEASE_PROG="${SCRIPT}"
 
-ERTS_VSN="10.6.4"
+ERTS_VSN="12.1.5"
 REL_DIR="$RELEASE_ROOT_DIR/releases/$REL_VSN"
 RUNNER_LOG_DIR="${RUNNER_LOG_DIR:-$RELEASE_ROOT_DIR/log}"
 export ESCRIPT_NAME="${ESCRIPT_NAME-$SCRIPT}"
@@ -208,8 +208,8 @@ find_erts_dir() {
             __erts_version="$("$__erl" -boot no_dot_erlang -sasl errlog_type error -noshell -eval "$erts_version_code")"
             ERTS_DIR="${__erl_root}/erts-${__erts_version}"
             if [ -d "$ERTS_DIR" ]; then
-                ERTS_VSN=${__erts_version}
                 echo "Exact ERTS version (${ERTS_VSN}) match not found, instead using ${__erts_version}. The release may fail to run." 1>&2
+                ERTS_VSN=${__erts_version}
             else
                 echo "Can not run the release. There is no ERTS bundled with the release or found on the system."
                 exit 1
@@ -328,8 +328,8 @@ erl_rpc() {
                 DYNAMIC_NAME="-r"
             fi
 
-            if [ "$ERL_DIST_PORT" ]; then
-                result=$("$ERL_RPC" "${DYNAMIC_NAME}" -c "${COOKIE}" -address "${ERL_DIST_PORT}" -timeout "${RELX_RPC_TIMEOUT}" -a "${command}")
+            if [ "$ADDRESS" ]; then
+                result=$("$ERL_RPC" "${DYNAMIC_NAME}" -c "${COOKIE}" -address "${ADDRESS}" -timeout "${RELX_RPC_TIMEOUT}" -a "${command}")
             else
                 result=$("$ERL_RPC" "$NAME_TYPE" "$NAME" "${DYNAMIC_NAME}" -c "${COOKIE}" -timeout "${RELX_RPC_TIMEOUT}" -a "${command}")
             fi
@@ -352,7 +352,7 @@ erl_eval() {
             command=$*
 
             if [ "$ERL_DIST_PORT" ]; then
-                result=$(echo "${command}" | "$ERL_RPC" "${DYNAMIC_NAME}" -c "${COOKIE}" -address "${ERL_DIST_PORT}" -timeout "${RELX_RPC_TIMEOUT}" -e)
+                result=$(echo "${command}" | "$ERL_RPC" "${DYNAMIC_NAME}" -c "${COOKIE}" -address "${ADDRESS}" -timeout "${RELX_RPC_TIMEOUT}" -e)
             else
                 result=$(echo "${command}" | "$ERL_RPC" "$NAME_TYPE" "$NAME" "${DYNAMIC_NAME}" -c "${COOKIE}" -timeout "${RELX_RPC_TIMEOUT}" -e)
             fi
@@ -410,6 +410,22 @@ relx_escript() {
     "$ERTS_DIR/bin/escript" "$ROOTDIR/$scriptpath" "$@"
 }
 
+# Convert {127,0,0,1} to 127.0.0.1 (inet:ntoa/1)
+addr_tuple_to_str() {
+    addr="$1"
+    saved_IFS="$IFS"
+    IFS="{,}'\" "
+    # shellcheck disable=SC2086
+    eval set -- $addr
+    IFS="$saved_IFS"
+
+    case $# in
+    4) printf '%u.%u.%u.%u' "$@";;
+    8) printf '%.4x:%.4x:%.4x:%.4x:%.4x:%.4x:%.4x:%.4x' "$@";;
+    *) echo "Cannot parse IP address tuple: '$addr'" 1>&2;;
+    esac
+}
+
 make_out_file_path() {
     # Use output directory provided in the RELX_OUT_FILE_PATH environment variable
     # (default to the current location of vm.args and sys.config)
@@ -435,6 +451,7 @@ replace_os_vars() {
             slen=split(var,arr,":-")
             v=arr[1]
             e=ENVIRON[v]
+            gsub("&","\\\\\\&",e)
             if(slen > 1 && e=="") {
                 i=index(var, ":-"arr[2])
                 def=substr(var,i+2)
@@ -596,7 +613,7 @@ RELX_CONFIG_PATH=$(check_replace_os_vars sys.config "$RELX_CONFIG_PATH")
 #    - nonexisting -args_files
 #    - circular dependencies of -args_files
 #    - relative paths in -args_file parameters
-#    - multiple/mixed occurences of -name and -sname parameters
+#    - multiple/mixed occurrences of -name and -sname parameters
 #    - missing -name or -sname parameters
 # If all checks pass, extract the target node name
 set +e
@@ -673,8 +690,17 @@ EPMD_MODULE="$(grep '^-epmd_module' "$VMARGS_PATH" || true)"
 if [ "$EPMD_MODULE" ]; then
     DIST_ARGS="${DIST_ARGS} ${EPMD_MODULE}"
 fi
+INET_DIST_USE_INTERFACE="$(grep '^-kernel  *inet_dist_use_interface' "$VMARGS_PATH" || true)"
+if [ "$INET_DIST_USE_INTERFACE" ]; then
+    DIST_ARGS="${DIST_ARGS} ${INET_DIST_USE_INTERFACE}"
+fi
 
 if [ "$ERL_DIST_PORT" ]; then
+    if [ "$INET_DIST_USE_INTERFACE" ]; then
+        ADDRESS="$(addr_tuple_to_str "${INET_DIST_USE_INTERFACE#*inet_dist_use_interface }"):$ERL_DIST_PORT"
+    else
+        ADDRESS="$ERL_DIST_PORT"
+    fi
     if [  "11.1" = "$(printf "%s\n11.1" "${ERTS_VSN}" | sort -V | head -n1)" ] ; then
         # unless set by the user, set start_epmd to false when ERL_DIST_PORT is used
         if [ ! "$START_EPMD" ]; then
@@ -683,6 +709,13 @@ if [ "$ERL_DIST_PORT" ]; then
             EXTRA_DIST_ARGS="-erl_epmd_port ${ERL_DIST_PORT}"
         fi
     else
+        ERL_DIST_PORT_WARNING="ERL_DIST_PORT is set and used to set the port, but doing so on ERTS version ${ERTS_VSN} means remsh/rpc will not work for this release"
+        if ! command -v logger > /dev/null 2>&1
+        then
+            echo "WARNING: ${ERL_DIST_PORT_WARNING}"
+        else
+            logger -p warning -t "${REL_NAME}[$$]" "${ERL_DIST_PORT_WARNING}"
+        fi
         EXTRA_DIST_ARGS="-kernel inet_dist_listen_min ${ERL_DIST_PORT} -kernel inet_dist_listen_max ${ERL_DIST_PORT}"
     fi
 fi
